package edu.sjsu.vmact.model;

public enum RuleId {
    CLUSTER_PARENT_CHILD,
    
    HYPOTHESIS_ACCOUNT_OR_COMMUNICATION_TRACE,
    HYPOTHESIS_WEB_ACTIVITY_TRACE,
    HYPOTHESIS_FILE_ACTIVITY_TRACE,
    HYPOTHESIS_DEVICE_INTERACTION_TRACE
}
